name: build-devcontainer
on:
  workflow_call:
    inputs:
      CLAB_VERSION:
        description: "Containerlab version"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      CLAB_VERSION:
        description: "Containerlab version"
        default: "0.59.0"
        required: false
        type: string

      TAG:
        description: "Additional container image tag"
        required: false
        type: string
  # trigger on published release event
  # to created the devspace container when the packages are published
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io

jobs:
  devcontainer:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
